/*
@fileSummary
This file is generated by "generateSchema.js" from the function chargerStructure().
Defines the chargerStructure object.
Intended for use in a browser.
*/
const chargerStructure = () => {
    const charger = {
        types: [],
        references: [],
        definitions: [],
        files: [],
    }
    const filterIgnore = () => Object.entries(charger);

    const ignoreKeys = {
        stash: (f) => ignoreKeys.stashes.push(f),
        stashes: [],
        onNonIgnore: (callback, type = "forEach") => filterIgnore()[type](callback),
        search: (origin) => {
            if(!origin.isGetter) return origin;
            
            for(const [_, check] of filterIgnore()) {
                const find = check.find(e => e.id == origin.for);
                if(find) return find;
            }
        }
    }
    ignoreKeys.ignoreKeys = [...Object.keys(ignoreKeys), "ignoreKeys"];
            

    return {
        ...charger,
        ...ignoreKeys,
    };
}